// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7MZ4994ihQLiozoCEMAsKKV7A7dkhIS4',
    appId: '1:535824677836:web:64e50c48365d43933a3b69',
    messagingSenderId: '535824677836',
    projectId: 'auraapp-3e734',
    authDomain: 'auraapp-3e734.firebaseapp.com',
    storageBucket: 'auraapp-3e734.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXkziHVOHfiGMPVQbBy3zMCZjpkQi2jU',
    appId: '1:535824677836:android:c807ae06fba163883a3b69',
    messagingSenderId: '535824677836',
    projectId: 'auraapp-3e734',
    storageBucket: 'auraapp-3e734.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBndxiOE_dyFxCgS3Yko9W6AgpvNbt6flk',
    appId: '1:535824677836:ios:17e8c00a0e573ad63a3b69',
    messagingSenderId: '535824677836',
    projectId: 'auraapp-3e734',
    storageBucket: 'auraapp-3e734.firebasestorage.app',
    iosBundleId: 'com.example.drmarmotino',
  );
}
